[admin]
cluster ansible_host=garage.link ansible_user=root ansible_ssh_private_key_file=~/.ssh/ansible

[builders]
yocto ansible_host=ymir ansible_user=ymir ansible_ssh_private_key_file=~/.ssh/ansible

# NOTE: there is a bug in sudo-rs that causes timeout when running sudo via ansible (https://github.com/ansible/ansible/issues/86849)
#       sudo-rs is used by default in ubuntu-26.04, but default sudo will be used if sudo-rs is removed, which fixes^
