services:
  rust-static-builder:
    image: ${CONTAINER_REGISTRY}/rust-static-builder:${IMG_TAG}
    build:
      context: ./dockerfiles/.
      dockerfile: rust-builder.Dockerfile
      target: final
