services:
  rust-dev:
    image: ${CONTAINER_REGISTRY}/rust-dev:${IMG_TAG}
    container_name: rust-dev
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: dockerfiles/rust-builder.Dockerfile
      target: dev
