# ---------------------------------------------------------------------------- #
FROM rust:alpine3.24@sha256:2ea3db105d38fdfa4e31f366674287fcaa828087e2fe3973befdc537f2d443b1 AS base
# ---------------------------------------------------------------------------- #
WORKDIR /app

RUN apk add --no-cache lld musl musl-dev clang git make ca-certificates

# mailcap is used for content type (MIME type) detection
# tzdata is used for timezones info
RUN apk add --no-cache ca-certificates mailcap tzdata
RUN update-ca-certificates

ENV USER=nonroot
ENV UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

RUN cargo install cargo-chef --version ^0.1

# ---------------------------------------------------------------------------- #
FROM base AS dev
# Specify this layer as the build target to create an image for rust dev.
# Subsequent layers are to be used by downstream consumers for building
# static binaries for their respective projects via the ONBUILD directives.
# ---------------------------------------------------------------------------- #
RUN cargo install --version="~0.8" sqlx-cli --no-default-features --features rustls,postgres
RUN rustup component add clippy
RUN rustup component add rustfmt
RUN cargo install cargo-audit
RUN cargo install just
RUN apk add --no-cache watchexec

# ---------------------------------------------------------------------------- #
FROM base AS onlydeps
# Use cargo chef to install only the project dependencies.
# This prevents full-project rebuilds when only source-code has changed.
# ---------------------------------------------------------------------------- #
ONBUILD COPY .cargo/ .cargo/
ONBUILD COPY Cargo.toml .
# compute project lock file
ONBUILD RUN cargo chef prepare --recipe-path recipe.json

# ---------------------------------------------------------------------------- #
FROM onlydeps AS builder
# This layer only rebuilds when there are source-code changes, or if the dependency
# cache generated by the previous target has changed.
# ---------------------------------------------------------------------------- #
ONBUILD COPY --from=onlydeps /app/recipe.json .
# only build project dependencies (this layer is only rebuilt when deps change)
ONBUILD RUN cargo chef cook --release --recipe-path recipe.json

# this layer is only rebuilt when source-code changes
ONBUILD COPY src/ src/
ONBUILD RUN cargo build --release

# ---------------------------------------------------------------------------- #
FROM scratch AS final
# Gather the statically built project binary, along with any other artifacts
# generated from previous stages that are required by the static binary.
# ---------------------------------------------------------------------------- #

# must match 'package.name' value in Cargo.toml
ONBUILD ARG APP_NAME

# /etc/mime.types may be used to detect the MIME type of files
COPY --from=base --chmod=444 /etc/passwd /etc/group /etc/mime.types /etc/

COPY --from=base --chmod=444 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=base --chmod=444 /usr/share/zoneinfo /usr/share/zoneinfo
ONBUILD COPY --from=builder /app/target/release/${APP_NAME} /bin/app

# Use an unprivileged user.
USER nonroot:nonroot

WORKDIR /app

ENTRYPOINT ["/bin/app"]
