---
- hosts: all
  become: yes

  tasks:
  - name: Ensure chrony (time sync) is installed.
    dnf: name=chrony state=present

  - name: Ensure chronyd daemon is running.
    service: name=chronyd state=started enabled=yes
